apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-label
  template:
    metadata:
      labels:
        app: game-label
    spec:
      containers:
      - image: alexwhen/docker-2048
        name: game
        ports:
        - containerPort: 80
          name: web
