apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: newdeal3-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-label
  template:
    metadata:
      labels:
        app: hello-label
    spec:
      containers:
      - image: hello-world
        name: hello
        ports:
        - containerPort: 80
          name: web
