apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeform-eks-deployment
  labels:
    app: kubeform-eks-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeform-eks-deployment
  template:
    metadata:
      labels:
        app: kubeform-eks-deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.21
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      - name: supermario
        image: pengbai/docker-supermario
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux