apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: game_nlb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: web
  selector: game_label
  type: LoadBalancer
