apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: mario_nlb
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: web
  selector: mario_label
  type: LoadBalancer
