apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: mario-nlb
  namespace: newdeal3-ns
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: web
  selector:
    app: mario-label
  type: LoadBalancer
