apiVersion: v1
kind: Namespace
metadata:
  name: nginx-ns
  labels:
    name: nginx-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario
  namespace: nginx-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mario_label
  template:
    metadata:
      labels:
        app: mario_label
    spec:
      containers:
        - name: supermario
          image: pengbai/docker-supermario
          ports:
            - name: web
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
  namespace: nginx-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game_label
  template:
    metadata:
      labels:
        app: game_label
    spec:
      containers:
        - name: game-2048
          image: alexwhen/docker-2048
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nlb
  namespace: nginx-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: mario_label
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-nlb2
  namespace: nginx-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  selector:
    app: game_label
  ports:
    - protocol: TCP
      port: 80
      targetPort: web